environments:
  kubernetes-environment:
    environment_variables:
      - NAMESPACE: gocd
      - DOCKERHUB_USERNAME: sheroy
    pipelines:
      - build_and_publish_image
      - deploy_to_kubernetes
pipelines:
   build_and_publish_image: # This is the name of the pipeline
      group: kubernetes-samples
      materials:
        mygit: #this is the name of the material
          # indicates the type of material and it's url
          git: https://github.com/gocd-demo/node-bulletin-board.git
      stages: # Stages run sequentially
        - build_and_publish_image: # this is the name of the stage
            jobs:
              build: # this is the name of the job
                  elastic_profile_id: demo-app # this is configured in the settings of the elastic agent for Kubernetes plugin
                  tasks:
                    - exec: # indicates the type of task
                        command: bash
                        arguments:
                          - "-c" # so we can specify the command to be run as a string
                          - "docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application"
                    - exec: # indicates the type of task
                        command: bash
                        arguments:
                          - "-c" # so we can specify the command to be run as a string
              publish_image: # this is the name of the job
                  elastic_profile_id: demo-app # this is configured in the settings of the elastic agent for Kubernetes plugin
                  tasks:
                    - exec: # indicates the type of task
                        command: bash
                        arguments:
                          - "-c" # so we can specify the command to be run as a string
                          - "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD"
                    - exec: # indicates the type of task
                        command: bash
                        arguments:
                          - "-c" # so we can specify the command to be run as a string
                          - "docker push $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL"
   
